platform :ios, '7.0'
inhibit_all_warnings!
use_frameworks!

target 'KSYLiveDemo' do
  pod 'Bugly'
  # YYImage is only used for importing gif and apng images in the demo format
  # If you don't need to support these formats, you don't need to add YYImage dependencies
  pod 'YYImage'
  # ZipArchive is only used to decompress resource files in the demo, not necessarily dependent
  pod 'ZipArchive', '~> 1.4'
  
  pod 'GPUImage'
  # KSYGPUResource is the basic version of the image resource, which contains the images that the beauty filter must rely on
  pod 'libksygpulive/KSYGPUResource',      :path => '/Users/taitruong/working/sizzl/app.sizzl.ios/sizzl/Vendor/KSYLive/'
  # KSYGPUResourceFull is the full version of image resources, including images of all special effects filters
  #pod 'libksygpulive/KSYGPUResourceFull',      :path => '../'
  ## Please select the resource package to add according to your needs, the increment of the full version of resource introduction is 3.1M

  pod 'libksygpulive/libksygpulive',       :path => '/Users/taitruong/working/sizzl/app.sizzl.ios/sizzl/Vendor/KSYLive/'
  # pod 'libksygpulive/libksygpulive_265', :path => '../'

  # The libraries of libksygpulive_ks3 and libksygpulive are exactly the same
  # It's just that the inventory of ks3 is placed on the domestic cloud disk, which is faster than github clone
  # pod 'libksygpulive_ks3/KSYGPUResource'
  # pod 'libksygpulive_ks3/libksygpulive'
end

target 'KSYLiveDemo_Swift' do
    pod 'Bugly'
    pod 'GPUImage'
    pod 'libksygpulive/KSYGPUResource', :path => '/Users/taitruong/working/sizzl/app.sizzl.ios/sizzl/Vendor/KSYLive/'
    pod 'libksygpulive/libksygpulive', :path => '/Users/taitruong/working/sizzl/app.sizzl.ios/sizzl/Vendor/KSYLive/'
    #pod 'libksygpulive/libksygpulive_265', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "!!!! #{target.name}"
  end
end
